### ISSUE TITLE
Please compile to the newer version (0.6)

### ISSUE THREAD

**Issue by ydkhatri** [Qazeer/usnjrnl_rewind_compiled#1]
I just updated with your pull request (bug fix) and another bug fix([Add reasons parsing](https://github.com/CyberCX-DFIR/usnjrnl_rewind/commit/cec4dca0b2d06665e9c9096ccddb9352175bc0d1)). Version is now 0.6

**Comment by Qazeer** [comment]
Just did with [usnjrnl_rewind v0.6 commit cec4dca](https://github.com/Qazeer/usnjrnl_rewind_compiled/releases/tag/v1.1_commit_cec4dca) release, thank you for the notice!
